---
# tasks file for appdb
- name: install postgres server
  yum:
    name: postgresql-server
    state: latest

- name: block to check state of database initialisation
  block:
    # Task to check whether of not the database has been initialised
    - name: check that the database was successfully initialised
      command: /usr/bin/postgresql-check-db-dir /var/lib/pgsql/data
      ignore_errors: yes
  rescue:
    - name: init check failed therefore initialising
      command: postgresql-setup initdb

- name: enable and start postgres
  service:
    name: postgresql.service
    state: started
    enabled: yes

