---
# Role to create the instances
- name: play to create instances from vars file
  hosts: workstation
  vars_files: osp_vars.yml
  tasks:
    - name: create instances
      os_server:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        flavor: "{{ item.flavor }}"
        nics: "{{ item.nics }}"
        key_name: "{{ item.key_name}}"
        security_groups: "{{ item.security_groups }}"
        meta: "{{ item.meta }}"
        state: present
      with_items: "{{ instances }}"
    - name: associate floating ip's
      os_floating_ip:
        state: present
        server: "{{ item.name }}"
        network: ext_network
        wait: true
        timeout: 180
        reuse: yes
      with_items: "{{ instances }}"
