---
# Role to create the instances
- name: role to create instances from vars file
  hosts: workstation
  vars_files: osp_vars.yml
  tasks:
    - name: delete floating ip's
      os_floating_ip:
         state: absent
         server: "{{ item.name }}"
         network: ext_network
         wait: true
         timeout: 180
      with_items: "{{ instances }}"
    - name: delete instances
      os_server:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        flavor: "{{ item.flavor }}"
        nics: "{{ item.nics }}"
        key_name: "{{ item.key_name}}"
        security_groups: "{{ item.security_groups }}"
        state: absent
      with_items: "{{ instances }}"
